name: Deploy static content to Pages

on:
  # Sadece main branch'e push yapılınca çalışır
  push:
    branches: ["main"]

  # Elle tetiklemeye izin verir
  workflow_dispatch:

# GitHub Pages'a deployment için gerekli izinler
permissions:
  contents: read
  pages: write
  id-token: write

# Aynı anda birden fazla deployment olmasın
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Eğer dosyaların kökteyse. (örn: index.html burada)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
